spring.application.name=ProductService

Logging.level.org.springframework.web = TRACE

# database properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/productservice
spring.datasource.username=productserviceuser_1
#spring.datasource.password=secret
